In [7]:
'''Q.1 Create a function based on the input and output. Look at the examples there is a pattern.'''

def secret(str1):
    res = ''
    for i in str1[2::]:
        if i == '.':
            res +=" "
        else:
            res +=i
            
    return f"secret({str1}) => <p class='{res}'></p>"

print(secret('p.one.two.three'))
print(secret('p.one'))
print(secret('p.four.five'))

secret(p.one.two.three) => <p class='one two three'></p>
secret(p.one) => <p class='one'></p>
secret(p.four.five) => <p class='four five'></p>


In [21]:
'''Q.2 Create a function which counts how many lone 1s appear in a given number. Lone means the number 
doesn't appear twice or more in a row.'''

def count_lone_ones(num):
    res = 0
    str_num = str(num)
    if str_num.count('1') != len(str_num):
        for i in range(len(str_num)-1):
            if str_num[i] =='1':
                if str_num[i+1] != '1':
                    res +=1
                else:
                    res = res -1
            else:
                if str_num[i+1] == '1':
                    res +=1

    return f"count_lone_ones({num}) => {res}"

print(count_lone_ones(101))
print(count_lone_ones(1191))
print(count_lone_ones(1111))
print(count_lone_ones(462))

count_lone_ones(101) => 2
count_lone_ones(1191) => 1
count_lone_ones(1111) => 0
count_lone_ones(462) => 0


In [16]:
'
a ='1111'
a.count('1')

4

In [17]:
'''Q.3 Write a method that accepts two integer parameters rows and cols. The output is a 2d array of numbers displayed
in column-major order, meaning the numbers shown increase sequentially down each column and wrap to the top of the next 
column to the right once the bottom of the current column is reached.'''

import numpy as np
def printGrid(row, column):
    num = [x for x in range(1, (row*column+1))]
    mat = np.array(num).reshape(column, row)
    return f"printGrid({row},{column})\n{np.transpose(mat)}\n"

print(printGrid(3,6))
print(printGrid(5,3))
print(printGrid(4,1))

printGrid(3,6)
[[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]]

printGrid(5,3)
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]

printGrid(4,1)
[[1]
 [2]
 [3]
 [4]]



In [30]:
'''Q.4 Given a list of integers, return the smallest positive integer not present in the list. Here is a representative example. Consider the list:
[-2, 6, 4, 5, 7, -1, 7, 1, 3, 6, 6, -2, 9, 10, 2, 2]
After reordering, the list becomes:
[-2, -2, -1, 1, 2, 2, 3, 4, 5, 6, 6, 6, 7, 7, 9, 10]
from which we see that the smallest missing positive integer is 8.'''

def min_miss_pos(list):
    range_list = [x for x in range(min(list), max(list)+1)]
    for i in range_list:
        if i>0:
            if i not in list:
                res = i
                break
    return f"min_miss_pose({list}) => {res}"       

print(min_miss_pos([-2,6,4,5,7,-1,1,3,6,-2,9,10,2,2]))
print(min_miss_pos([5, 9, -2, 0, 1, 3, 9, 3, 8, 9]))
print(min_miss_pos([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9]))

min_miss_pose([-2, 6, 4, 5, 7, -1, 1, 3, 6, -2, 9, 10, 2, 2]) => 8
min_miss_pose([5, 9, -2, 0, 1, 3, 9, 3, 8, 9]) => 2
min_miss_pose([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9]) => 1


In [9]:
'''Q.5 Google is launching a network of autonomous pizza delivery drones and wants you to create a flexible rewards 
system (Pizza Points™) that can be tweaked in the future. The rules are simple: if a customer has made at least N
orders of at least Y price, they get a FREE pizza! Create a function that takes a dictionary of customers, a minimum 
number of orders and a minimum order price. Return a list of customers that are eligible
for a free pizza.'''

def pizza_point(customer, min_order, min_price):
    length_dict = {key: len([i for i in value if i>min_price])
                   for key, value in customers.items()}

    if length_dict['Batman'] == length_dict['Spider-Man']:
        if length_dict['Batman'] >0:
            res = ['Batman', 'Spider-Man']
        else:
            res = []
    elif length_dict['Batman'] > length_dict['Spider-Man']:
        res = ['Batman']

    elif length_dict['Batman'] < length_dict['Spider-Man']:
        res = ['Spider-Man']
    
    return f"pizza_point(customers, {min_order}, {min_price}) => {res}"

customers = {
"Batman": [22, 30, 11, 17, 15, 52, 27, 12],
"Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10,11,45]
}

print(pizza_point(customers, 5, 20))
print(pizza_point(customers, 3, 10))
print(pizza_point(customers, 5, 100))

pizza_point(customers, 5, 20) => ['Spider-Man']
pizza_point(customers, 3, 10) => ['Batman', 'Spider-Man']
pizza_point(customers, 5, 100) => []
