In [19]:
'''Q.1 Create a function that transposes a 2D matrix.'''

import numpy
def transpose_matrix(two_d_array):
    res = numpy.transpose(two_d_array)
    return f"transpose_matrix\nQuestion\n{numpy.array(two_d_array)}\nAnswer\n{res}"

print(transpose_matrix([[1,1,1],[2,2,2],[3,3,3]]))

transpose_matrix
Question
[[1 1 1]
 [2 2 2]
 [3 3 3]]
Answer
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
'''Q.2. Create a function that determines whether a string is a valid hex code. A hex code must begin with a pound key # 
and is exactly 6 characters in length. Each character must be a digit from 0-9 or an alphabetic character from A-F. 
All alphabetic characters may be uppercase or lowercase.'''

import string
def is_valid_hex_code(code):
    condition1 = string.digits
    condition2 = string.ascii_lowercase[:6] + string.ascii_uppercase[:6]
    condition = condition1 + condition2
    d = 0
    result = "Flase"
    if code[0] == '#':
        if len(code[1::]) == 6:
            for i in range(1, len(code)):
                if code[i] in condition:
                    d = d + 1
    
    if d == 6:
        result = "True"
    return f"is_valid_hex_code({code}) => {result}"

print(is_valid_hex_code('#CD5C5C'))
print(is_valid_hex_code('#CD5C58C'))
print(is_valid_hex_code('#eaecee'))
print(is_valid_hex_code('#CD5C&C'))
print(is_valid_hex_code('#eaecee'))
print(is_valid_hex_code('#CD5ZC5'))

is_valid_hex_code(#CD5C5C) => True
is_valid_hex_code(#CD5C58C) => Flase
is_valid_hex_code(#eaecee) => True
is_valid_hex_code(#CD5C&C) => Flase
is_valid_hex_code(#eaecee) => True
is_valid_hex_code(#CD5ZC5) => Flase


In [12]:
'''Q3. Given a list of math equations (given as strings), return the percentage of correct answers as a string. 
Round to the nearest whole number.'''

import re
def mark_math(list1):
    res = 0
    for i in list1:
        if '+' in i:
            split = re.split("[+=]",i)
            tools = int(split[0]) + int(split[1])
            if tools == int(split[2]):
                res = res + 1
        elif '-' in i:
            split = re.split("[-=]",i)
            tools = int(split[0]) - int(split[1])
            if tools == int(split[2]):
                res = res + 1
                
    result = (res/len(list1))*100
    return f"mark_math({list1}) => {round(result)}%"

print(mark_math(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]))
print(mark_math(["1-2=2"]))
print(mark_math(["2+3=5", "4+4=9", "3-1=2"]))

mark_math(['2+2=4', '3+2=5', '10-3=3', '5+5=10']) => 75%
mark_math(['1-2=2']) => 0%
mark_math(['2+3=5', '4+4=9', '3-1=2']) => 67%


In [5]:
'''Q.4 There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out one particular row 
in the grid (say the second row) byb putting either a 1 or a 0 in each box, such that the sum of the numbers in that
row is odd. The referee tells Bob to fill out one column in the grid (say the first column) by putting either a 1 or a 0 
in each box, such that the sum of the numbers in that column is even. Alice and Bob win the game if Alice’s numbers give 
an odd sum, Bob’s give an even sum, and (most important) they’ve each written down the same number in the one square 
where their row and column intersect.'''

def magic_squre_game(list1, list2):
    row = list1[0]
    column = list2[0]
    
    res = 'False'
    if list1[1][column-1] == list2[1][row-1]:
        res = 'True'
    return f"magic_square_game({list1}, {list2}) => {res}"

print(magic_squre_game([2,'100'],[1,'101']))
print(magic_squre_game([2,'001'],[1,'101']))   
print(magic_squre_game([3,'111'],[2,'011']))  
print(magic_squre_game([1,'010'],[3,'101']))   

magic_square_game([2, '100'], [1, '101']) => False
magic_square_game([2, '001'], [1, '101']) => True
magic_square_game([3, '111'], [2, '011']) => True
magic_square_game([1, '010'], [3, '101']) => False
